# Generated by Django 6.0.7 on 2026-08-01 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctor",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctor",
            name="name",
            field=models.CharField(default="Unknown Doctor", max_length=100),
        ),
        migrations.AddField(
            model_name="staff",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staff",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Other", "Other")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="staff",
            name="name",
            field=models.CharField(default="Unknown Staff", max_length=100),
        ),
    ]
